pipeline {
    agent any
environment {
		DOCKERHUB_CREDENTIALS=credentials('dockerhub-cred')
	}
    stages {
        stage('Clone repository') {
            steps {
                sh "rm -rf *"
               sh "git clone https://github.com/psdike/cicd-projects.git"
               
                //sh "cd cicd-projects"
               
            }
        }

        stage('Build Docker image') {
            
            steps {
                sh 'ls -la'
                sh 'docker build -t psdike/php:v${BUILD_NUMBER} -f cicd-projects/first-cicd-jenkins-docker-route53/Dockerfile .'
            }
        }

        stage('Login & Push Docker image') {
            
            steps {
 				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'

                sh 'docker push psdike/php:v${BUILD_NUMBER}'
            }
        }
        stage('Run Docker container') {
            steps {
//                 sh 'docker rm -f $(docker ps -a -q)'
                sh 'docker run -d -p 80:80 psdike/php:v${BUILD_NUMBER}'
            }
        }

        stage('Show success message') {
            steps {
                echo 'Docker container is running at http://prod.reliabledevops.in'
            }
        }
    }
}
